app:
  image: 'firstandthird/node:6.10-3-nobuild'
  command: "npm run dev:server" #if you don't want clientkit
  volumes:
    - '.:/home/app/src'
  links:
    - 'db:mongo'
  environment:
    PORT: 8080
    VIRTUAL_HOST: 'micro-metrics.*'
  ports:
    - '8080'
db:
  image: 'mongo'
  command: 'mongod --smallfiles --quiet'
