app:
  build: .
  command: 'nodemon index.js'
  volumes:
    - '.:/app/server'
  links:
    - 'db:mongo'
  environment:
    PORT: 8081
  ports:
    - '8081:8081'
db:
  image: 'mongo'
  command: 'mongod --quiet'
