app:
  image: 'firstandthird/node:8.2.1-dev'
  volumes:
    - '.:/home/app/src'
  links:
    - 'db:mongo'
  environment:
    PORT: 8080
    VIRTUAL_HOST: 'micro-metrics.*'
    FORCE_COLOR: 1
  ports:
    - '8080'
db:
  image: 'mongo'
  command: 'mongod --smallfiles --quiet'
