app:
  build: .
  command: "nodemon ../node_modules/.bin/rapptor"
  volumes:
    - '.:/app/server'
    - '/app/node_modules'
  links:
    - 'db:mongo'
  environment:
    PORT: 8081
  ports:
    - '8081:8081'
db:
  image: 'mongo'
  command: 'mongod --quiet'
