host: 'http://{{env.virtualHost}}'
mongo:
  url: "{{env.mongoFile ? readFile(env.mongoFile) : env.mongoUrl }}"

plugins:
  hapi-req:
    localPrefix: '{{routePrefix}}'
  hapi-mongodb:
    url: "{{mongo.url}}"
  hapi-method-loader:
    _dependencies:
      - "hapi-mongodb"
      - "hapi-mongodb-collections"
  hapi-mongodb-collections:
    namespace: 'db'
    collections:
      - 'tracks'
  hapi-mongo-indexes:
    collections:
      tracks:
        - keys:
            createdOn: 1
        - keys:
            type: 1
            createdOn: 1
  hapi-swaggered:
    requiredTags: []
    info:
      title: 'Micro Metrics'
      version: '1.0'
    schemes:
      - 'http'
      - 'https'
