
host: 'http://{{ENV.VIRTUAL_HOST}}'
connection:
  port: '{{ENV.PORT}}'
mongo:
  host: "{{ENV.MONGO_PORT_27017_TCP_ADDR}}"
  port: "{{ENV.MONGO_PORT_27017_TCP_PORT}}"
  db: "micrometrics"
  url: "mongodb://{{mongo.host}}:{{mongo.port}}/{{mongo.db}}"

plugins:
  hapi-auto-handler:

  hapi-logr:
    renderOptions:
      console:
        timestamp: false
  hapi-mongodb:
    _priority: -5
    url: "{{mongo.url}}"
  hapi-mongodb-collections:
    _priority: -4
    namespace: 'db'
    collections: 
      - 'tracks'
