
host: 'http://{{ENV.VIRTUAL_HOST}}'
connection:
  port: '{{ENV.PORT}}'
mongo:
  host: "{{ENV.MONGO_PORT_27017_TCP_ADDR}}"
  port: "{{ENV.MONGO_PORT_27017_TCP_PORT}}"
  db: "micrometrics"
  url: "mongodb://{{mongo.host}}:{{mongo.port}}/{{mongo.db}}"

plugins:
  vision:
  inert:
  hapi-mongodb:
    url: "{{mongo.url}}"

views:
  engines:
    html: 'handlebars'
  path: 'public/pages'
  helpersPath:
    - 'node_modules/handlebar-helpers'
    - 'helpers'

assets:
  path: 'public/_dist'
  endpoint: '/ui'
