
host: 'http://{{ENV.VIRTUAL_HOST}}'
connection:
  port: '{{ENV.PORT}}'
mongo:
  url: "{{ENV.MONGO_URL || 'mongodb://mongo:27017/micrometrics'}}"

plugins:
  hapi-auto-handler:
    _priority: -3
  hapi-mongodb:
    _priority: -5
    url: "{{mongo.url}}"
  hapi-mongodb-collections:
    _priority: -4
    namespace: 'db'
    collections: 
      - 'tracks'
