plugins:
  hapi-auto-handler:
    _priority: -1
  hapi-req:
    _priority: -2
    localPrefix: '{{routePrefix}}'
  hapi-mongodb:
    _priority: -3
    url: "{{mongo.url}}"
  hapi-method-loader:
    _priority: -2
  hapi-mongodb-collections:
    _priority: -3
    namespace: 'db'
    collections:
      - 'tracks'
  hapi-mongo-indexes:
    collections:
      tracks:
        - keys:
            createdOn: 1
        - keys:
            type: 1
            createdOn: 1
  hapi-swaggered:
    requiredTags: []
    info:
      title: 'Micro Metrics'
      version: '1.0'
    schemes:
      - 'http'
      - 'https'
