
host: 'http://{{ENV.VIRTUAL_HOST}}'
connection:
  port: '{{ENV.PORT}}'
mongo:
  host: "{{ENV.MONGO_PORT_27017_TCP_ADDR}}"
  port: "{{ENV.MONGO_PORT_27017_TCP_PORT}}"
  db: "micrometrics"
  url: "mongodb://{{mongo.host}}:{{mongo.port}}/{{mongo.db}}"

plugins:
  hapi-mongodb:
    url: "mongodb://{{mongo.host}}:{{mongo.port}}/{{mongo.db}}"
